/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentationLayer;

import BussinesLayer.ActividadAñoBO;
import DataTransferObject.ActividadAño;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author MIGUEL
 */
public class FrmActividadesGrafica extends javax.swing.JFrame {

    void ajustarTabla() {
        TableColumnModel columnModel = tablaactividad.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(180);
        columnModel.getColumn(2).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(10);
    }
    /**
     * Creates new form FrmActividadesGrafica
     */
    public FrmActividadesGrafica() {
        initComponents();
         ajustarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaactividad = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        comboxbuscar = new javax.swing.JComboBox<>();

        buscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-búsqueda-48 (1).png"))); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(136, 220, 101));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TABLA DE ACTIVIDADES");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione el Año:");

        buscar1.setBackground(new java.awt.Color(153, 255, 153));
        buscar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buscar1.setForeground(new java.awt.Color(255, 102, 102));
        buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-búsqueda-48 (1).png"))); // NOI18N
        buscar1.setText("Buscar");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });

        tablaactividad.setBackground(new java.awt.Color(153, 255, 153));
        tablaactividad.setForeground(new java.awt.Color(0, 0, 0));
        tablaactividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Actividad", "monto", "Año"
            }
        ));
        jScrollPane1.setViewportView(tablaactividad);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jButton2.setText("Mostrar Gráfica");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboxbuscar.setBackground(new java.awt.Color(153, 255, 153));
        comboxbuscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboxbuscar.setForeground(new java.awt.Color(255, 102, 102));
        comboxbuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022" }));
        comboxbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxbuscarActionPerformed(evt);
            }
        });
        comboxbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboxbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboxbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar1)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buscar1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    }//GEN-LAST:event_buscarActionPerformed

    private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1ActionPerformed
            try {
                ArrayList<ActividadAño>actividadesAños= null;
                String cadena= (String) comboxbuscar.getSelectedItem();
                DefaultTableModel modelo = (DefaultTableModel)tablaactividad.getModel();
                modelo.setRowCount(0);

                ActividadAñoBO actividadAñoBO = new ActividadAñoBO();
                actividadesAños= new ArrayList<>();
                actividadesAños=actividadAñoBO.buscarActividadAño(cadena);

               for(ActividadAño act: actividadesAños){
                    Object[]registro={
                    tablaactividad.getRowCount()+1    
                        ,act.getActividad().getNombre_actividad()
                        ,act.getMonto()
                        ,act.getAño().getAño()
                    };
                    modelo.addRow(registro);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
            }            
    }//GEN-LAST:event_buscar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultCategoryDataset dato= new DefaultCategoryDataset();
        try{ 
            for(int i=0;i<tablaactividad.getRowCount();i++){
                dato.addValue(Double.parseDouble(tablaactividad.getValueAt(i,2).toString()),
                tablaactividad.getValueAt(i,1).toString(), 
                tablaactividad.getValueAt(i,3).toString());
                
            }
        
        JFreeChart grafico_barras= ChartFactory.createBarChart3D(
            "Grafica de Actividades", //nombre del gráfico
            "Visitas", //nombre de las barras o columnas        
            "Dias", //nombre de la numeracion
            dato,  //datos del grafico
            PlotOrientation.VERTICAL, //orientacion
            true, //legenda de barras individuales por color
            true, //herramientas 
            true //url grafico
        ); 
        ChartFrame panel=new ChartFrame("Grafica de Actividades",grafico_barras);
            panel.setSize(800,600);
            panel.setLocationRelativeTo(null);
            panel.setVisible(true);
        }catch(Exception e){
          System.out.println(e);
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboxbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboxbuscarKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            try {
                ArrayList<ActividadAño>actividadesAños= null;
                String cadena= (String) comboxbuscar.getSelectedItem();
                DefaultTableModel modelo = (DefaultTableModel)tablaactividad.getModel();
                modelo.setRowCount(0);

                ActividadAñoBO actividadAñoBO = new ActividadAñoBO();
                actividadesAños= new ArrayList<>();
                actividadesAños=actividadAñoBO.buscarActividadAño(cadena);

                for(ActividadAño act: actividadesAños){
                    Object[]registro={
                    tablaactividad.getRowCount()+1    
                        ,act.getActividad().getNombre_actividad()
                        ,act.getMonto()
                        ,act.getAño().getAño()
                    };
                    modelo.addRow(registro);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
            }
        }           
    }//GEN-LAST:event_comboxbuscarKeyReleased

    private void comboxbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActividadesGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActividadesGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActividadesGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActividadesGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActividadesGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar1;
    private javax.swing.JComboBox<String> comboxbuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaactividad;
    // End of variables declaration//GEN-END:variables
}
