/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentationLayer;

import BussinesLayer.CuentaAñoBO;
import DataTransferObject.CuentaAño;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author MIGUEL
 */
public class FrmRazonLiquidez extends javax.swing.JFrame {
    public FrmRazonLiquidez() {
        initComponents();
        mostrar21();
        mostrar22();
        ajustarTabla();
    }
     void ajustarTabla() {
        TableColumnModel columnModel = tablacuenta21.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(80);
        columnModel.getColumn(2).setPreferredWidth(140);
        columnModel.getColumn(3).setPreferredWidth(80);
        
        TableColumnModel columnModels = tablacuenta22.getColumnModel();
        columnModels.getColumn(0).setPreferredWidth(30);
        columnModels.getColumn(1).setPreferredWidth(80);
        columnModels.getColumn(2).setPreferredWidth(140);
        columnModels.getColumn(3).setPreferredWidth(80);
    }    
    public void mostrar21(){
        try {
                ArrayList<CuentaAño>cuentasAño= null;
                String cadena= (String) txtestado.getText();
                DefaultTableModel modelo = (DefaultTableModel)tablacuenta21.getModel();
                modelo.setRowCount(0);

                CuentaAñoBO cuentaAñoBO = new CuentaAñoBO();
                cuentasAño= new ArrayList<>();
                cuentasAño=cuentaAñoBO.buscarCuenta(cadena);

               for(CuentaAño p: cuentasAño){
                    Object[]registro={
                    tablacuenta21.getRowCount()+1    
                        ,p.getEstado().getNombre_estado()
                        ,p.getCuenta().getNombre_cuenta()
                        ,p.getMonto21()
                    };
                    modelo.addRow(registro);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
            }           
    }
    public void mostrar22(){
        try {
                ArrayList<CuentaAño>cuentasAño= null;
                String cadena= (String) txtestado.getText();
                DefaultTableModel modelo = (DefaultTableModel)tablacuenta22.getModel();
                modelo.setRowCount(0);

                CuentaAñoBO cuentaAñoBO = new CuentaAñoBO();
                cuentasAño= new ArrayList<>();
                cuentasAño=cuentaAñoBO.buscarCuenta22(cadena);

               for(CuentaAño p: cuentasAño){
                    Object[]registro={
                    tablacuenta22.getRowCount()+1    
                        ,p.getEstado().getNombre_estado()
                        ,p.getCuenta().getNombre_cuenta()
                        ,p.getMonto21()
                    };
                    modelo.addRow(registro);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Aviso",JOptionPane.ERROR_MESSAGE);
            }        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacuenta21 = new javax.swing.JTable();
        txtestado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacuenta22 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprc21 = new javax.swing.JTextField();
        txtac21 = new javax.swing.JTextField();
        txtpc21 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtct21 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtac22 = new javax.swing.JTextField();
        txtpc22 = new javax.swing.JTextField();
        txtct22 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtprc22 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        gaugeChart2 = new chart.GaugeChart();
        gaugeChart1 = new chart.GaugeChart();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Capital de Trabajo - Prueba Circulante");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 450, 30));
        jPanel3.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 403, -1, -1));

        tablacuenta21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Estado", "Cuenta", "Monto 2021"
            }
        ));
        tablacuenta21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacuenta21MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacuenta21);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 320, 170));

        txtestado.setEditable(false);
        txtestado.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        txtestado.setForeground(new java.awt.Color(255, 102, 102));
        txtestado.setText("Situacional");
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        jPanel3.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Estado:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        tablacuenta22.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Estado", "Cuenta", "Monto 2022"
            }
        ));
        tablacuenta22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacuenta22MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablacuenta22);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 320, 170));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Razon Liquidez 2021"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Prueba Cir 2021");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Activos Corrientes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pasivo Corrientes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtprc21.setEditable(false);
        txtprc21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprc21ActionPerformed(evt);
            }
        });
        jPanel1.add(txtprc21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, 30));

        txtac21.setEditable(false);
        jPanel1.add(txtac21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 30));

        txtpc21.setEditable(false);
        jPanel1.add(txtpc21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cap Trabajo 2021");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtct21.setEditable(false);
        txtct21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtct21ActionPerformed(evt);
            }
        });
        jPanel1.add(txtct21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 320, 220));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Razon Liquidez 2022"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Activos Corrientes");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Pasivo Corrientes");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cap Trabajo 2022");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtac22.setEditable(false);
        txtac22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtac22ActionPerformed(evt);
            }
        });
        jPanel2.add(txtac22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        txtpc22.setEditable(false);
        jPanel2.add(txtpc22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, 30));

        txtct22.setEditable(false);
        jPanel2.add(txtct22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 120, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Prueba Cir 2022");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtprc22.setEditable(false);
        txtprc22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprc22ActionPerformed(evt);
            }
        });
        jPanel2.add(txtprc22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 320, 210));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Calcular CT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jButton2.setText("Graficar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, 50));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Semáforo 2021");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Semáforo 2022");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        gaugeChart2.setColor1(new java.awt.Color(118, 189, 34));
        jPanel3.add(gaugeChart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 190, 160));

        gaugeChart1.setColor1(new java.awt.Color(118, 189, 34));
        jPanel3.add(gaugeChart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 190, 160));

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 153));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        jTabbedPane2.addTab("Razon Liquidez", jPanel3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1053, 595));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultCategoryDataset dato= new DefaultCategoryDataset();
        try{

            double n1=Double.parseDouble(txtac21.getText());
            double n2=Double.parseDouble(txtpc21.getText());
            double n3=Double.parseDouble(txtct21.getText());
            double n4=Double.parseDouble(txtprc21.getText());
            
            double m1=Double.parseDouble(txtac22.getText());
            double m2=Double.parseDouble(txtpc22.getText());
            double m3=Double.parseDouble(txtct22.getText());
            double m4=Double.parseDouble(txtprc22.getText());
            
            DefaultCategoryDataset datos= new DefaultCategoryDataset();

            datos.setValue(n1, "Activo Corriente", "2021");
            datos.setValue(n2, "Pasivo Corriente", "2021");
            datos.setValue(n3, "Capital Trabajo", "2021");
            datos.setValue(n4, "Prueba Circulante","2021");
            
            datos.setValue(m1, "Activo Corriente", "2022");
            datos.setValue(m2, "Pasivo Corriente", "2022");
            datos.setValue(m3, "Capital Trabajo", "2022");
            datos.setValue(m4, "Prueba Circulante","2022");
            
            JFreeChart grafico_barras= ChartFactory.createBarChart3D(
                "Razon de Liquidez", //nombre del gráfico
                "Visitas", //nombre de las barras o columnas
                "Dias", //nombre de la numeracion
                datos,  //datos del grafico
                PlotOrientation.VERTICAL, //orientacion
                true, //legenda de barras individuales por color
                true, //herramientas
                true //url grafico
            );
            ChartFrame panel=new ChartFrame("Razon de Liquidez",grafico_barras);
            panel.setSize(700,500);
            panel.setLocationRelativeTo(null);
            panel.setVisible(true);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            double n1=Double.parseDouble(txtac21.getText());
            double n2=Double.parseDouble(txtpc21.getText());
            double n3;
            double n4;
            double m1=Double.parseDouble(txtac22.getText());
            double m2=Double.parseDouble(txtpc22.getText());
            double m3;
            double m4;
            n3= n1-n2;
            m3= m1-m2;
            n4=Math.round(((n1/n2)*100));
            m4=Math.round(((m1/m2)*100));
            txtprc21.setText(String.valueOf(n4));
            txtprc22.setText(String.valueOf(m4));
            txtct22.setText(String.valueOf(m3));     
            txtct21.setText(String.valueOf(n3)); 
            gaugeChart1.setValueWithAnimation((int)n4);  
            gaugeChart2.setValueWithAnimation((int)m4);  
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtac22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtac22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtac22ActionPerformed

    private void txtprc21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprc21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprc21ActionPerformed

    private void tablacuenta22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacuenta22MouseClicked
        txtac22.setText(tablacuenta22.getValueAt(0, 3).toString());
        txtpc22.setText(tablacuenta22.getValueAt(2, 3).toString());
    }//GEN-LAST:event_tablacuenta22MouseClicked

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void tablacuenta21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacuenta21MouseClicked
        txtac21.setText(tablacuenta21.getValueAt(0, 3).toString());
        txtpc21.setText(tablacuenta21.getValueAt(2, 3).toString());
    }//GEN-LAST:event_tablacuenta21MouseClicked

    private void txtct21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtct21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtct21ActionPerformed

    private void txtprc22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprc22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprc22ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       SistemaBSCMenu ventana= new SistemaBSCMenu();
       ventana.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRazonLiquidez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRazonLiquidez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRazonLiquidez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRazonLiquidez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRazonLiquidez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private chart.GaugeChart gaugeChart1;
    private chart.GaugeChart gaugeChart2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tablacuenta21;
    private javax.swing.JTable tablacuenta22;
    private javax.swing.JTextField txtac21;
    private javax.swing.JTextField txtac22;
    private javax.swing.JTextField txtct21;
    private javax.swing.JTextField txtct22;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtpc21;
    private javax.swing.JTextField txtpc22;
    private javax.swing.JTextField txtprc21;
    private javax.swing.JTextField txtprc22;
    // End of variables declaration//GEN-END:variables
}
